### ISSUE TITLE
DDIM sampler produces weird/non-coherent images

### ISSUE THREAD

**Issue by NickLucche** [NickLucche/stable-diffusion-nvidia-docker#13]
Might be due to default args we're using when creating the sampler

**Comment by mchaker** [comment]
Link to example: https://github.com/NickLucche/stable-diffusion-nvidia-docker/issues/8#issuecomment-1242704221

**Comment by NickLucche** [comment]
fixed with https://github.com/NickLucche/stable-diffusion-nvidia-docker/commit/78b2c50b427efb67d2b04f44e73118acaa0a45c5#diff-8b284a9000a48c1f05058b897e9be2511ba66dea116da0dcc6d0764e418bf7ee

**Comment by mchaker** [comment]
Thank you! :)
