### ISSUE TITLE
Re-structure the "Samples" section of the README

### ISSUE THREAD

**Issue by mchaker** [NickLucche/stable-diffusion-nvidia-docker#15]
https://github.com/NickLucche/stable-diffusion-nvidia-docker/issues/8#issuecomment-1245030154

> re-structure the "Samples" section of the README to showcase some of the things you can do with stable diffusion, like fixing a seed and gradually increasing the guidance scale to get results that are progressively "closer" to the prompted input. I think some tips like that could be useful

**Comment by mchaker** [comment]
Actually, checking the README, this seems to already be done?

**Comment by NickLucche** [comment]
Yep I'll close this for now, let me know if you find other tricks worth showcasing :)
