### ISSUE TITLE
FP16=0 not working for me

### ISSUE THREAD

**Issue by RobertSvebeck** [NickLucche/stable-diffusion-nvidia-docker#2]
I successfully created the container as the default docker run... command but when I tried setting it up again using the FP16=0 part I get an error "docker: invalid reference format: repository name must be lowercase.". 

perhaps I am misunderstanding how to use the variable as I am just getting started with containers in general....

here is my command: docker run --name stablediffusion --gpus all -it -e FP16=0 TOKEN=mytokenhere -p 7860:7860 nicklucche/stable-diffusion

I also tried adding the variable with quotes but it didn¨t work.. any suggestions? (I have a12 GB GPU)

**Comment by NickLucche** [comment]
Hi, you need to prepend each environment variable you set with `-e`, here we're setting two of them so this should be 
`docker run --name stablediffusion --gpus all -it -e FP16=0 -e TOKEN=mytokenhere -p 7860:7860 nicklucche/stable-diffusion`
(notice the `-e` before the TOKEN variable).

Let me know if that works for you

**Comment by RobertSvebeck** [comment]
Hi! Oh yes, that worked. Thanks!
