### ISSUE TITLE
Can this work with novelai-leak model?

### ISSUE THREAD

**Issue by g0g5** [NickLucche/stable-diffusion-nvidia-docker#23]
Sorry to ask such an taboo topics... In other words, how to use this with local models?

**Comment by Anonym0us33** [comment]
seconding this

**Comment by NickLucche** [comment]
I will update on this topic on related issue https://github.com/NickLucche/stable-diffusion-nvidia-docker/issues/28. I will add support for models that can be loaded with `diffusers` library.
