### ISSUE TITLE
Support of AUTOMATIC1111/stable-diffusion-webui

### ISSUE THREAD

**Issue by alexchenyu** [NickLucche/stable-diffusion-nvidia-docker#24]
Hi Nick, 
Really appreciate this project. Someone from Nvidia recommends this to me.
I am wondering does this support AUTOMATIC1111? Because looks like that one is really popular and have rich functions.

**Comment by NickLucche** [comment]
Hi, thanks for that!
This repo does not support the code provided by AUTOMATIC1111, don't they provide a docker image with similar capabilities?
