### ISSUE TITLE
 Invalid rev id: fp16

### ISSUE THREAD

**Issue by MastaDan9** [NickLucche/stable-diffusion-nvidia-docker#26]
Hi. How do I upload other models? I always get the error "Invalid rev id: fp16" there is no file on the path ".../resolve/fp16/model_index.json."
![image](https://github.com/NickLucche/stable-diffusion-nvidia-docker/assets/7467926/da7b1a72-084f-4ea2-9486-3cd1c5e21a7e)

**Comment by NickLucche** [comment]
this means there no fp16 model, try to disable fp16 loading with 
`docker run .. -e FP16=0 ...`
